server:
  port: 8080


spring:
  application:
    name: sampleredisapp


redis:
  sentinel:
    master: mymaster
    nodes: "127.0.0.1:5000,127.0.0.1:5001,127.0.0.1:5003"


ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true